CC-15652 Unzer Credentials GUI
spryker-eco/unzer-gui pull request #4
Opened 2022-02-03 14:04 UTC by kkicheglovspryker

https://spryker.atlassian.net/browse/CC-15652

2022-02-22 13:24 UTC, michbeck commented on composer.json
> +        "spryker-eco/unzer": "dev-feature/cc-14610/cc-15652-unzer-credentials-gui as 1.0",
Please don't forget to change back before merge

2022-02-22 13:46 UTC, AsonUnique commented on assets/Zed/js/modules/main.js
> + * Copyright (c) 2016-present Spryker Systems GmbH. All rights reserved.
It looks like the copyright is incorrect

2022-02-22 13:46 UTC, AsonUnique commented on assets/Zed/js/spryker-zed-unzer-gui-main.entry.js
> + * Copyright (c) 2016-present Spryker Systems GmbH. All rights reserved.
It looks like the copyright is incorrect

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/AbstractUnzerCredentialsController.php
> +    public const PARAM_ID_UNZER_CREDENTIALS = 'id-unzer-credentials';
move public constants above protected ones, please

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/CreateMerchantUnzerCredentialsController.php
> +    protected function createUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
```suggestion
    protected function handleUnzerCredentialsForm(Request $request, FormInterface $unzerCredentialsForm)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/CreateMerchantUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
can we specify array structure here?

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/CreateUnzerCredentialsController.php
> +    protected function createUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
```suggestion
    protected function handleUnzerCredentialsForm(Request $request, FormInterface $unzerCredentialsForm)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/CreateUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
Can we specify array structure here?

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMarketplaceUnzerCredentialsController.php
> +    protected function updateUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
```suggestion
    protected function handleUnzerCredentialsForm(Request $request, FormInterface $unzerCredentialsForm)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMarketplaceUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
same question about array structure

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMarketplaceUnzerCredentialsController.php
> +     * @return array
```suggestion
     * @return array<string, mixed>
```
?

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMerchantUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
same

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMerchantUnzerCredentialsController.php
> +    protected function updateUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
```suggestion
    protected function handleUnzerCredentialsForm(Request $request, FormInterface $unzerCredentialsForm)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMerchantUnzerCredentialsController.php
> +    protected function getForm(UnzerCredentialsFormDataProvider $unzerCredentialsFormDataProvider, int $idUnzerCredentials): FormInterface
looks like proxy method

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMarketplaceUnzerCredentialsController.php
> +    protected function getForm(UnzerCredentialsFormDataProvider $unzerCredentialsFormDataProvider, int $idUnzerCredentials): FormInterface
looks like proxy method

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditStandardUnzerCredentialsController.php
> +    protected function updateUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
```suggestion
    protected function handleUnzerCredentialsForm(Request $request, FormInterface $unzerCredentialsForm)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditStandardUnzerCredentialsController.php
> +    protected function getForm(UnzerCredentialsFormDataProvider $unzerCredentialsFormDataProvider, int $idUnzerCredentials): FormInterface
same

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/SuggestMerchantController.php
> +     * @return array
Specify array structure, please

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Finder/MerchantReferenceFinder.php
> +    ) {
```suggestion
    public function __construct(UnzerGuiToMerchantFacadeInterface $merchantFacade)
    {
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Finder/MerchantReferenceFinder.php
> +        $labelTemplate = '%s (%s)';
There's no need for this variable

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/AbstractUnzerCredentialsForm.php
> +    protected function addIdUnzerCredentialsField(FormBuilderInterface $builder): self
```suggestion
    protected function addIdUnzerCredentialsField(FormBuilderInterface $builder)
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/AbstractUnzerCredentialsForm.php
> +     * @return static
```suggestion
     * @return $this
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/AbstractUnzerCredentialsForm.php
> +     * @return static
```suggestion
     * @return $this
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/Constraint/UnzerCredentialsConstraintValidator.php
> +            $text = strtr((string)$messageTransfer->getValue(), $messageTransfer->getParameters());
I guess you can use `setParameters` method of `ConstraintViolationBuilderInterface` instead of this.

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/DataProvider/MerchantUnzerFormDataProvider.php
> +class MerchantUnzerFormDataProvider1
I assume this class can be removed

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/DataProvider/UnzerCredentialsFormDataProvider.php
> +     * @return array
```suggestion
     * @return array<string, mixed>
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/MerchantUnzerCredentialsCreateForm.php
> +     * @return $this
looks redundant

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/MerchantUnzerCredentialsCreateForm.php
> +     * @param array $choices
can we specify an array structure?

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/MerchantUnzerCredentialsEditForm.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/UnzerCredentialsCreateForm.php
> +     * @param array $choices
same here

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/UnzerCredentialsCreateForm.php
> +                    self::MERCHANT_REFERENCE_CHOICES_OPTION => $builder->getOption(self::MERCHANT_REFERENCE_CHOICES_OPTION),
```suggestion
                    static::MERCHANT_REFERENCE_CHOICES_OPTION => $builder->getOption(static::MERCHANT_REFERENCE_CHOICES_OPTION),
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/UnzerKeypairType.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/UnzerMainMerchantCredentialsType.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Form/UnzerMainMerchantCredentialsType.php
> +     * @param array $choices
same here

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/AnotherMerchantUnzerCredentialsTable.php
> +    public const COL_ACTIONS = 'actions';
Please, move public constants above protected.

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/AnotherMerchantUnzerCredentialsTable.php
> +//        $this->unzerCredentialsQuery
please, remove this

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/AnotherMerchantUnzerCredentialsTable.php
> +        unset($queryResults);
Not sure that you need it

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/MerchantUnzerCredentialsTable.php
> +        unset($queryResults);
not sure that you need it

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/UnzerCredentialsTable.php
> +        unset($queryResults);
not sure that you need it

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +    public function createUnzerCredentialsFormTabs(): UnzerCredentialsFormTabs
```suggestion
    public function createUnzerCredentialsFormTabs(): TabsInterface
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +     * @param array $options
```suggestion
     * @param array<string, mixed> $options
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/UnzerGuiConfig.php
> +     * @var array
```suggestion
     * @var array<int, string>
```

2022-02-22 13:46 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/UnzerGuiConfig.php
> +     * @var array
Also, move protected method below public ones

2022-02-22 13:48 UTC, michbeck commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/AnotherMerchantUnzerCredentialsTable.php
> +
Can this be removed at all?

2022-02-23 10:02 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/CreateUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
```suggestion
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array<string,mixed>
```

2022-02-23 10:02 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditMarketplaceUnzerCredentialsController.php
> +     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array
```suggestion
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|array<string,mixed>
```

2022-02-23 10:02 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Controller/EditStandardUnzerCredentialsController.php
> +    protected function updateUnzerCredentials(Request $request, FormInterface $unzerCredentialsForm)
What about this one?

2022-02-23 11:57 UTC, AsonUnique approved these changes

2022-02-23 12:56 UTC, michbeck approved these changes

2022-02-25 08:23 UTC, dmytro-sokolovskyi requested changes

2022-02-25 08:23 UTC, dmytro-sokolovskyi commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +    public function createDeleteUnzerCredentialsForm(): FormInterface
createDeleteUnzerCredentialsForm() -> getUnzerCredentialsDeleteForm()

2022-03-01 11:10 UTC, michbeck commented on src/SprykerEco/Zed/UnzerGui/Communication/UnzerGuiCommunicationFactory.php
> +    public function createDeleteUnzerCredentialsForm(): FormInterface
Fixed.

2022-03-02 08:03 UTC, dmytro-sokolovskyi approved these changes

2022-03-04 14:10 UTC, merged