[WIP] CC-14716: OMS Order commands
spryker-eco/unzer-gui pull request #7
Opened 2022-03-21 16:44 UTC by michbeck

https://spryker.atlassian.net/browse/CC-14716

2022-04-05 08:11 UTC, AsonUnique commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/MerchantUnzerCredentialsTable.php
> +            SpyUnzerCredentialsTableMap::COL_ID_UNZER_CREDENTIALS => 'Credential List Id',
Please, update translation files accordingly

2022-04-06 08:59 UTC, dmiseev approved these changes

2022-04-06 09:01 UTC, kkicheglovspryker commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/MerchantUnzerCredentialsTable.php
> +            SpyUnzerCredentialsTableMap::COL_ID_UNZER_CREDENTIALS => 'Credential List Id',
Done

2022-04-06 09:10 UTC, AsonUnique approved these changes

2022-04-06 09:58 UTC, DmitryLymarenko requested changes

2022-04-06 09:58 UTC, DmitryLymarenko commented on src/SprykerEco/Zed/UnzerGui/Communication/Table/MerchantUnzerCredentialsTable.php
> +            SpyUnzerCredentialsTableMap::COL_PUBLIC_KEY => 'Public Key',
translation is missing

2022-04-07 07:35 UTC, DmitryLymarenko approved these changes

2022-04-12 06:28 UTC, merged